#生产环境配置文件

#服务配置
server:
   port: 7900
   servlet:
      context-path: /fl

#spring配置
spring: 
   #数据源配置
   datasource: 
      url: jdbc:mysql://localhost:3306/pump?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root

#属性配置      
minMoney: 1
description: 最少金额为：${minMoney}

#对象配置（spring boot 2.x 中对配置文件中名称的命名规范进行了强制约束，
#需要使用kebab格式，不能使用java中的驼峰式写法了，分隔符使用 ’-‘ 来分隔）
amount-config:
   minAmount: 1
   maxAmount: 99
   remark: 最小金额为：${amount-config.minAmount}，最大金额为：${amount-config.maxAmount}